### ISSUE TITLE
Fine tuning the model

### ISSUE THREAD

**Issue by bharat-patidar** [at16k/at16k-t2t-helpers#3]
Hi @mohitsshah ,

Thanks for providing model and helper scripts.
Just wanted to know, how can we fine tune this model on custom dataset?
Can you please guide me how to use model architecture of trained model to retrain model for a specific dataset 

Thanks

**Comment by mohitsshah** [comment]
The model is a Tensor2Tensor model using the same library. Check out tensor2tensor to understand how to retrain or add your own dataset, etc.
